### PR TITLE
Cleanup init.d and ebuild

### PR DESCRIPTION
**Pull request by brandondahler**
forked-daapd.init.d:
- Change default main file to /etc/forked-daapd.d/forked-daapd.conf (was referencing non-existent file /etc/forked-daapd.conf)
- Depend on avahi-daemon so it automatically starts with forked-daapd

forked-daapd.0.19-r1.ebuild:
- Rename /etc/forked.daapd.d/ to /etc/forked-daapd.d

### CODE REVIEW

**Comment by saintdev** [comment]
There needs to be some sort of warning that the default config location has changed. An ewarn in pkg_postinst should be fine.
Copying existing config files (if they are found) from $ROOT to their new locations in $D might be a good idea as well.

Also, could you squash these two commits together. I would prefer to keep Manifest updates with their respective changes.

**Comment by brandondahler** [comment]
I've added copying of the old default config and the old config directory to the new ones if they exist and added warning messages about it.

Let me know if there's anything else needed.

Edit:  Fixed git problems and additionally, I made the new and old default config files so that they are 600 instead of 700.

**Comment by brandondahler** [comment]
Is there anything else needed for this?

**Comment by saintdev** [comment]
Sorry I haven't gotten to this yet. I've been busy. I'll try and look it over in a few days.

**Pull request closed without merging**
